// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAWOz4WReTs1AWUjbn2-OrsH_ydVhlw-cM',
    appId: '1:921795702733:web:4e50570c52e8f285bd1e84',
    messagingSenderId: '921795702733',
    projectId: 'ucv-restaurant',
    authDomain: 'ucv-restaurant.firebaseapp.com',
    storageBucket: 'ucv-restaurant.firebasestorage.app',
    measurementId: 'G-S8KZEDTRC4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyClMvaNdXv1n-WpEVjUpNeDGGhLtb1sIjs',
    appId: '1:921795702733:android:9a51520d154a2af8bd1e84',
    messagingSenderId: '921795702733',
    projectId: 'ucv-restaurant',
    storageBucket: 'ucv-restaurant.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCkuL-frOeeMPHAglA5UeFTinqlJH8e5xY',
    appId: '1:921795702733:ios:76a66f06d6b3605fbd1e84',
    messagingSenderId: '921795702733',
    projectId: 'ucv-restaurant',
    storageBucket: 'ucv-restaurant.firebasestorage.app',
    iosBundleId: 'com.example.taully',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyAWOz4WReTs1AWUjbn2-OrsH_ydVhlw-cM',
    appId: '1:921795702733:web:05c66a9eb21074a9bd1e84',
    messagingSenderId: '921795702733',
    projectId: 'ucv-restaurant',
    authDomain: 'ucv-restaurant.firebaseapp.com',
    storageBucket: 'ucv-restaurant.firebasestorage.app',
    measurementId: 'G-8XL3NFV7CG',
  );

}